export const customerConstants = {
	CUSTOMER_FETCH_SERVICES:'CUSTOMER_FETCH_SERVICES',
	CUSTOMER_FETCH_SERVICE:'CUSTOMER_FETCH_SERVICE',
	CUSTOMER_SEARCH_SERVICE:'CUSTOMER_SEARCH_SERVICE',
	CUSTOMER_UPDATE_SERVICE: 'CUSTOMER_UPDATE_SERVICE',


	CUSTOMER_SELECT_SERVICE_RESERVATION: 'CUSTOMER_SELECT_SERVICE_RESERVATION',
	CUSTOMER_SELECT_DATE_RESERVATION: 'CUSTOMER_SELECT_DATE_RESERVATION',
	CUSTOMER_SELECT_START_TIME_RESERVATION: 'CUSTOMER_SELECT_TIME_RESERVATION',
	CUSTOMER_SELECT_END_TIME_RESERVATION: 'CUSTOMER_SELECT_END_TIME_RESERVATION',
	CUSTOMER_SELECT_EMPLOYEE_RESERVATION: 'CUSTOMER_SELECT_EMPLOYEE_RESERVATION',
}