export const ownerConstants = {
    OWNER_FETCH_SERVICES:'OWNER_FETCH_SERVICES',	
    OWNER_FETCH_SERVICE_EMPLOYEES:'OWNER_FETCH_SERVICES_EMPLOYEES',
    OWNER_CREATE_SERVICE: 'OWNER_CREATE_SERVICE',
    OWNER_DELETE_SERVICE: 'OWNER_DELETE_SERVICE',
	OWNER_UPDATE_SERVICE: 'OWNER_UPDATE_SERVICE'
}