export const ownerConstants = {
    OWNER_FETCH_SERVICES:'OWNER_FETCH_SERVICES',    
    OWNER_CREATE_SERVICE: 'OWNER_CREATE_SERVICE',
    OWNER_DELETE_SERVICE: 'OWNER_DELETE_SERVICE',
    OWNER_UPDATE_SERVICE: 'OWNER_UPDATE_SERVICE',
    OWNER_ADD_EMPlOYEE_SERVICE:'OWNER_ADD_EMPlOYEE_SERVICE',
    OWNER_FETCH_SERVICE_HISTORY:'OWNER_FETCH_SERVICE_HISTORY',
}