export const userConstants = {
	REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

	FETCH_PROFILE: 'USER_FETCH_PROFILE',
	FETCH_USER_RESERVATIONS: 'USER_FETCH_RESERVATIONS',
	LOGOUT: 'USER_LOGOUT',
}