export const userConstants = {
	REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

	FETCH_PROFILE: 'USER_FETCH_PROFILE',
	FETCH_USER_RESERVATIONS: 'USER_FETCH_RESERVATIONS',
	ADMIN_FETCH_COMPLAINTS: 'ADMIN_FETCH_COMPLAINTS',
	ADMIN_FETCH_USERS: 'ADMIN_FETCH_USERS',
	EDIT_REQUEST: 'USER_EDIT_REQUEST',
	EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
	EDIT_FAILURE: 'USER_EDIT_FAILURE',

	LOGOUT: 'USER_LOGOUT',
}