export const userConstants = {
	REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

	ADMIN_FETCH_COMPLAINTS: 'ADMIN_FETCH_COMPLAINTS',
	ADMIN_FETCH_USERS: 'ADMIN_FETCH_USERS',

	LOGOUT: 'USER_LOGOUT',
}